### ISSUE TITLE
Search and download in BYOD

### ISSUE THREAD

**Issue by emmaladolphi** [switchonproject/cids-custom-switchon#147] opened 2016-06-22 12:19 UTC
When using the BYOD search eg. 'E-PRTR v.3.3' you first reach a list with possible resources. Here one can press a small download icon to download the resource (see fig 1 'Tools'). However when pressing info to reach the resource there is no link available (see fig 2 'Datasets') neither format. This is the case for many resources.

This is very variable between datasets, some only have the icon, and some only have the link when going to the info page. The download option should be available both at the table site (fig1) and the info page (fig 2). The format information is only available when the dataset has a link at the info page.

This should be rectified to you can use download for both pages and so that all information is obtainable.

Fig 1:
![download icon](https://cloud.githubusercontent.com/assets/8414617/16266118/7e0d67f0-3883-11e6-9676-c74b986bbc4d.png)

Fig 2:
![no download link](https://cloud.githubusercontent.com/assets/8414617/16266124/87b4908a-3883-11e6-827e-fafec80aafba.png)

**Comment by p-a-s-c-a-l** [comment] 2016-06-22 13:47
Confirmed Bug. Duplicate of https://github.com/switchonproject/cids-custom-switchon/issues/150

**Closed by p-a-s-c-a-l** 2016-06-22 13:47 UTC
Labels: bug, duplicate
