### ISSUE TITLE
Error when adding dataset to wizard

### ISSUE THREAD

**Issue by emmaladolphi** [switchonproject/cids-custom-switchon#132] opened 2015-07-06 07:02 UTC
When adding datasets "Generation of a digital global map of artificially drained agricultural areas" (see row 153-160 in spreadsheet Batch E) they appear to be added as the rest, however when later searching in the wizard and BYOD no results are found. Is the dataset added but the search function doesn't work in this case, or wasn't that dataset added? This is a bug. Why wasn't these particular datasets not added while all the others were (when all boxes were correctly filled in). 

A difference between these datasets and the rest are the title length. If this is a factor an error message should be shown when adding the dataset. An error message should also appear if the dataset isn't added.

**Comment by p-a-s-c-a-l** [comment] 2015-07-06 09:46
Probably a problem wit X-CUAHSI. I deployed a new release. Please try again to add one such dataset. If the problem still persists and no error message is shown after adding the dataset in the wizard, please sent me the file c:\navigator.log

**Comment by emmaladolphi** [comment] 2015-07-06 10:43
Still not able to add it. This message shows up:
![not found](https://cloud.githubusercontent.com/assets/8414617/8520637/5f1b7d08-23dc-11e5-97dc-56983a69c2d9.jpg)

Link to batch: https://docs.google.com/spreadsheets/d/1CMUDM9NizHotPrErnhqhZng6kWvryeAErZLOT_IkyKc/edit#gid=0

**Comment by p-a-s-c-a-l** [comment] 2015-07-06 12:08
I need the logfile


Am 06.07.2015 um 12:43 schrieb emmaladolphi:
>
> Still not able to add it. This message shows up:
> not found 
> <https://cloud.githubusercontent.com/assets/8414617/8520637/5f1b7d08-23dc-11e5-97dc-56983a69c2d9.jpg>
>
> Link to batch: 
> https://docs.google.com/spreadsheets/d/1CMUDM9NizHotPrErnhqhZng6kWvryeAErZLOT_IkyKc/edit#gid=0
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/switchonproject/cids-custom-switchon/issues/132#issuecomment-118806020>.
>


-- 
Pascal Dihé

cismet GmbH
http://www.cismet.de

Hochschul-Technologie-Zentrum
Altenkesseler Str. 17, Geb. D2
66115 Saarbrücken, Germany

Phone +49 681 96590123

**Comment by p-a-s-c-a-l** [comment] 2015-07-06 12:16
OK. The problem is the resource title. It's not just "Generation of a digital global map of artificially drained agricultural areas" but e.g. *"Generation of a digital global map of artificially drained agricultural areas, Data set 8: fraction of each 5 arc min x 5 arc min grid cell artificially drained for countries in which a dinstinction of drainage of irrigated areas and drainage of rainfed areas was not possible*" 

This is far too long! Maximum length of the resource name must not exceed 140 chars. Furthermore, resources names that are that long cannot be rendered properly in the clients. Even if such a name is shortened by the client , the user will just see several entries "Generation of a digital global map...", which is not useful at all.

Are you sure that this isn't the description? If not, please shorten to a reasonable size.

**Comment by emmaladolphi** [comment] 2015-07-06 12:41
Ok, I will shorten it! However it could be useful to get an error message
or make it impossible to press next when an erroneous text is added?

Best wishes // Emma

2015-07-06 14:16 GMT+02:00 Pascal Dihé <notifications@github.com>:

**Comment by p-a-s-c-a-l** [comment] 2015-07-06 12:45
Thanks! I wonder why not why no error message pops up. I'll check this.

**Comment by p-a-s-c-a-l** [comment] 2015-07-07 09:58
Resolved in https://github.com/switchonproject/cids-custom-switchon/issues/136

**Closed by p-a-s-c-a-l** 2015-07-07 09:58 UTC
