### ISSUE TITLE
Top menu/field turns grey and unclickable

### ISSUE THREAD

**Issue by emmaladolphi** [switchonproject/cids-custom-switchon#23] opened 2014-08-11 09:48 UTC
Class: System Error
e.g. "Feature Request", "System Error", "Serious Bug"

Product:SWITCH-On Demo Application   Version:SIP 0,1 or 1,0 SNAPSHOT
Browser:Google Chrome                Version:36.0.1985.125 m   

Is it reproducible: Yes

Steps to Produce/Reproduce
--------------------------
Start program. Resources -> SWITCH-On -> External -> AMSR-E/AE_Land3. Double-click first item in the list. In the top field/menu go to Window. Click on Map (which makes the map disappear). Click on Map again. In the top field File, Edit, History, GeoSearch, Bookmark, Extras, Window, and Help are now grey, unclickable. 

Expected Results
----------------
To make the map box disappear and then come back again.

Actual Results
--------------
Makes the previoulsy clickable top field categories "File, Edit, History, GeoSearch, Bookmark, Extras, Window, and Help"  grey and unclickable. Can not find a way to get them back. 

Workarounds
-----------

Attachments
-----------
![image](https://cloud.githubusercontent.com/assets/8414617/3874091/5a9d95de-213c-11e4-99b7-cc91acd8f276.png)

Other Information
-----------------

**Comment by p-a-s-c-a-l** [comment] 2015-02-16 13:15
Duplicate of https://github.com/cismet/cids-navigator/issues/110

**Closed by p-a-s-c-a-l** 2015-02-16 13:15 UTC
Labels: bug, confirmed, duplicate
